# Generated by Django 4.0.5 on 2022-08-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='photo',
        ),
    ]
